### ISSUE TITLE
Functions on the global scope

### ISSUE THREAD

**Issue by poshest** [brandonroberts/angularjs-component-router#1]
Hey @brandonroberts, I'm sorry to abuse your github issues like this, but I'm following your great example that you've given in this repo, and wanted to ask if you know why the standard convention for Angular code emerging in last year or so is to declare the controller functions on the global scope?  Eg as in your code 

```
angular.module('app.admin', []).component('admin', {
   ...
    controller: AdminController,
   ...
});

function AdminController() { // function is on the global scope
}
```

As far as I've ever known, this is bad practice.  Any idea how has it become widespread practice in Angular?

**Comment by brandonroberts** [comment]
@poshest I do agree thats its bad practice. I think its best practice to organize your angular code this way though.  One if not the most well known style guide follows this, but he recommends avoid the functions being on the global scope by wrapping them in a closure. I just haven't done that here as this is meant to be an example of using the router, not necessarily building an entire angular app.

Style guide: https://github.com/johnpapa/angular-styleguide

**Comment by poshest** [comment]
OK, thanks for clarifying and for the link @brandonroberts. It's good to revisit that after a while.  It's a pretty comprehensive styleguide now.  :)
