### ISSUE TITLE
Component route x bindings

### ISSUE THREAD

**Issue by lucianogreiner** [brandonroberts/angularjs-component-router#10]
Hi Brandon.

Is there a way to pass in component bindings along with a routeconfig?

I have this scenario i am struggling to fit under routing scenarion while trying to make components as independent as possible having bindings for input/ouput:

```
// activated via /order/1
app.component('order', {
    template : '
        <h2>Order</h2>
          <div><customer-info customer="$ctrl.customer"></customer-info></div>
          <div><order-products products="$ctrl.products" on-add="$ctrl.productAdded(product)"...</order-products></div>',
    bindings : {
       id : '<'
    },
    controller : function() {
        this.customer = { ... };
        this.products = [ {...}, ... ];
    }
});

//"order-products" component switches between "product-list" and "product-editor" components
app.component('orderProducts', {
    template : '<product-list products="$ctrl.products" on-click="$ctrl.edit"></product-list></product-editor product="$ctrl.product"></product-editor>',
    bindings : {
        products : '<',
        onAdd : '&'
    },
    controller : function() {
        ...
        this.edit = function() {
           ...
        }
    }
});
```

My question is: 
How would i be able to call /order/1/products to make order-products display only its product-list (default) and /order/1/products/20 to have order-products to display product-editor for product 20?

So i tried:

```
app.component('orderProducts', {
    template : '<div ng-outlet></div>',
    bindings : {
        products : '<',
        onAdd : '&'
    },
    controller : function() {
       ...
    },
    $routeConfig : [
    { path: '/', component: 'productList', name: 'ProductList' //, ? bindings },
    { path: '/:id', component: 'productEditor', name: 'ProductEditor' //, ? bindings  }
    ]
});
```

So, if i want to keep productList and productEditor independent, how could i pass on their bindings "products" and "product" respectively from orderProducts ?

**Comment by brandonroberts** [comment]
Hi Luciano,

You can't provide bindings for route components. The route components are compiled dynamically, so there isn't a way to pass bindings to them. If you need access to the route parameters, you need to use the $routerOnActivate lifecycle hook, which is called right after the route is loaded.

```
// activated via /order/1
app.component('order', {
    template : '
          <h2>Order</h2>
          <div><customer-info customer="$ctrl.customer"></customer-info></div>
          <div><order-products products="$ctrl.products" on-add="$ctrl.productAdded(product)"...</order-products></div>',
    controller : function() {
        this.$routerOnActivate = function(current, previous) {
            this.id = current.params.id;
        }
        this.customer = { ... };
        this.products = [ {...}, ... ];
    }
});
```

If you treat your route components more as containers, with your display components in them, its easier to pass data to those display components.

I hope this helps

**Comment by winnemucca** [comment]
Hey Brandon this is very helpful.  I am looking at 

```
function(current, previous) {}

```

and am wondering on the  **$routerOnActivate** if we can/should treat **current** similar to **toState in $stateChangeSuccess**  on **ui-router**?

I am wondering this in the sense of handling values such as

```
if(current.name === 'changeInfo') {
    $scope.loading = true;
    $scope.showForm = false;
}

```

The if statement would exist inside of the $routerOnActivate method similar to ui-routers stateChange Success

```
   $scope.on('$stateChangeSuccess', function(event, toState) {
    if(to.State.name === 'changeInfo') {
    // change info would be a component filled with a form
    }
}
```

**Comment by brandonroberts** [comment]
@winnemucca Yea, you could treat it that way. Its only scoped to that component unlike $stateChangeSuccess which is a global event. So in the $routerOnActivate you'd already know that you're "changeInfo" route component.

``` js
// in the changeInfo route component
var ctrl = this;
ctrl.$routerOnActivate = function(next, previous) {
    ctrl.loading = true;
    ctrl.showForm = false;
};
```

**Comment by brandonroberts** [comment]
@winnemucca Did that help with your issue?

**Comment by winnemucca** [comment]
Yeah, big thanks.  The component router is a bit simpler than ui-router.  Seems like the life cycle hooks are  also doing the work of resolves as well.

**Comment by brandonroberts** [comment]
Cool, yep
