### ISSUE TITLE
Component attributes

### ISSUE THREAD

**Issue by char0n** [brandonroberts/angularjs-component-router#12]
Hi,

I am trying to use ngComponentRouter in angular1.5 application.  Here is my sample code.

``` javascript
(function() {
  'use strict';

  angular
    .module('components')
    .component('tzApp', tzAppFactory());

  function tzAppFactory() {
    return {
      class: 'test',
      template:
        '<tz-toolbar></tz-toolbar>' +
        '<main flex layout="column" layout-fill ng-outlet></main>',
      $routeConfig: [
        {
          path: '/chat/inbox/...',
          component: 'tzInbox',
          name: 'TzInbox',
          useAsDefault: true
        }
      ]
    };
  }
})();
```

When this code is executed following html code is created

``` html
<tz-toolbar></tz-toolbar>
<main flex layout="column" layout-fill ng-outlet>
  <tz-inbox>some inner content</tz-inbox
</main>
```

My question is: is there any way to to pass some additional attributes to tzInbox component ? For example what I want to do is to attach another attribute directive on this component while it is beying created. My result should look like this for example:

``` html
<tz-toolbar></tz-toolbar>
<main flex layout="column" layout-fill ng-outlet>
  <tz-inbox flex class="flex">some inner content</tz-inbox
</main>
```

Is is event possible or am I missing something ?

Thank you for any answer

**Comment by brandonroberts** [comment]
@char0n There is no event that will let you do that. The component element is generated dynamically, so no you cannot pass additional attributes to the `tzInbox` component. You would have use to DOM to query for the `tz-inbox` element and attach your extra attributes that way.

**Comment by winnemucca** [comment]
@char0n @brandonroberts can 

```
.component('tzApp', tzAppFactory());

```

tzAppFactory()
be a function?

**Comment by brandonroberts** [comment]
@winnemucca Sure, as long as it returns the component object

**Comment by winnemucca** [comment]
thanks!

**Comment by char0n** [comment]
@brandonroberts thanks for the answer. I suspected it after viewing the source code of the router. Can you think of any workaround for this ? I know I can manipulate the DOM in $onInit event, but in this specific case I want to attach flex directive from angular material, which makes the element flex. I was unsuccessfully trying to use .directive (with replace: true) instead of .component, but the router just don't like the directives at all. The only workaround I can think of is to attach the directive to the component at runtime, which creates a lot of overhead.

Thanks

**Comment by brandonroberts** [comment]
@char0n one option would be to use your routes more like containers. 

``` js
(function() {
  'use strict';

  angular
    .module('components')
    .component('tzApp', tzAppFactory());

  function tzAppFactory() {
    return {
      class: 'test',
      template:
        '<tz-toolbar></tz-toolbar>' +
        '<main flex layout="column" layout-fill ng-outlet></main>',
      $routeConfig: [
        {
          path: '/chat/inbox/...',
          component: 'tzInboxRoute',
          name: 'TzInbox',
          useAsDefault: true
        }
      ]
    };
  }
})();
```

Then your `tzInboxRoute` component template contains

``` html
     <tz-inbox flex class="flex">some inner content</tz-inbox>
```

Might be less hassle than doing it at runtime

**Comment by char0n** [comment]
Thanks, but would be resulting html again be like ?

``` html
<tz-inbox-route>
    <tz-inbox flex class="flex">some inner content</tz-inbox>
</tz-inbox-route>
```

The main problem is with flex boxes. Every parent must be of class layout and must flex. I guest I can overcome this problem in angular material by manually attaching css classes flex\* and layout-\* in $onInit lifecycle event.

**Comment by brandonroberts** [comment]
@char0n you're right. I was treating the tz-inbox-route just like a placeholder, but you need the topmost element to be flexed.

**Comment by brandonroberts** [comment]
What if you add your own directive that finds the first element after each ng-outlet and attaches the attributes you need to it after each route change?

**Comment by char0n** [comment]
I will can try this approach also. Thank you. 

One more question. Is there a way to have multiple named ng-outlet directives in one template on the version of router currently sitting in this repo  ?

**Comment by brandonroberts** [comment]
No, multiple named outlets are not supported in the ng1 component router yet.

**Comment by char0n** [comment]
Thanks for all the answers and your time. I managed to get the router working with angular 1.5 and angular material except the templateUrl bug which is being merged from pull request today I guess.

**Comment by brandonroberts** [comment]
Cool :+1:

**Comment by mika-fischer** [comment]
@char0n How did you fix this in the end? I'm having exactly the same problem and see no way to solve it sanely...

**Comment by char0n** [comment]
@mika-fischer checkout this gist: https://gist.github.com/anonymous/7e2b6127b8f9345ad30487012a6e9235

The part that may interest you is on line 40. Basically element is reference to your host component and it is a jQuery object. If you also need to attach directives on runtime, it can also be done, but currently in my project I don't have a use case for it so neither the example.

Hope it helps.

**Comment by mika-fischer** [comment]
@char0n That works well, as a workaround, thanks!

**Comment by mika-fischer** [comment]
Another possibility is to use the injectability of component templates. I.e. instead of setting the template directly, set it to a function returning the template string. This function can be injected with `$element` and/or `$attrs`.

``` javascript
function processTemplate(template, opts) {
    opts = opts || {};
    return ($element, $attrs) => {
        'ngInject';

        if (opts.classes) {
            $attrs.$addClass(opts.classes);
        }

        return template;
    };
}

angular.module('app.views.events', [])
    .component('eventsListView', {
        controller: EventsListController,
        template: processTemplate(EventsListTemplate, { classes: 'flex layout-column' })
    })
```

**Comment by char0n** [comment]
Yep, nice one also ! ;]

Shame it doesn't allow dynamically attaching the directives to host component.
