### ISSUE TITLE
$routeConfig no longer work since $rootRouter update

### ISSUE THREAD

**Issue by sylvaindumont** [brandonroberts/angularjs-component-router#14]
To configure routes, we need to use  $rootRouter.config([]),
and we cannot configure nested routes without $routeConfig on the component.

**Comment by sylvaindumont** [comment]
It works fine with the demo, but in my case even with the same components, the problem must come from a conflict with a dependency, or from the typescript compilation.

**Comment by sylvaindumont** [comment]
It just require angular 1.5.1, it doesn't work with angular 1.5.0.

**Comment by brandonroberts** [comment]
Thanks for pointing that out. I'm just point to the latest angular snapshot, which is why I didn't see it.
