### ISSUE TITLE
Uncaught TypeError: angular.module(...).component is not a function

### ISSUE THREAD

**Issue by packadal** [brandonroberts/angularjs-component-router#2]
Hey,

I'm getting this error on a recent build of your demo app, any thoughts ?

Uncaught TypeError: angular.module(...).component is not a function

Thanks for the demo app, its very useful to me :)

**Comment by brandonroberts** [comment]
@packadal Did you make any changes? I'm using that latest snapshot of angular which has the component function.

**Comment by packadal** [comment]
I didn't make any changes, except trying to use angularjs 1.5 rc0,  which
has this function also, but still I get this error.

**Comment by brandonroberts** [comment]
@packadal I tried it with 1.5 rc0 and it worked fine for me. Show me what changes you made.

**Comment by packadal** [comment]
I only amde changes after I got the error.

I tried again by cleaning the repo and re-doing the npm install and gulp
and now it worked.

Sorry for the bother.

**Comment by brandonroberts** [comment]
:+1:

**Comment by winnemucca** [comment]
@brandonroberts 
So I did a clean install getting a npm warning

npm WARN EPACKAGEJSON angularjs-component-router@0.1.0 No repository field.

Not sure what to put in the package.json file to remove the warning.  Seems like that would be the cause for the two existing errors.

**Comment by brandonroberts** [comment]
@winnemucca I'm just missing a repository section in my package.json. It wouldn't cause those errors though

**Comment by winnemucca** [comment]
@brandonroberts  Just set up your repo on my own by writing similar files.  Not sure what was going on with my pull.  I noticed that you used a directive on index.html.  Is this a more idealistic approach than using ng-outlet?

**Comment by brandonroberts** [comment]
@winnemucca its more in line with how Angular 2 is set up with a root component containing your application.
