### ISSUE TITLE
Navigate in a dialog

### ISSUE THREAD

**Issue by vguede** [brandonroberts/angularjs-component-router#3]
Hi @brandonroberts !
Do you know how can I open a dialog (with $mdDialog) who performs a navigation ?
For example, there is a list of objects in a view, and when I choose Delete, it opens a dialog with a new component to confirm.

**Comment by brandonroberts** [comment]
@vguede you could inject the router into your $mdDialog controller and use it to navigate based on a click action in your dialog.

**Comment by vguede** [comment]
@brandonroberts Thanks !
Another question...
How can I do a redirect ($router.navigate()) in $onActivate hook ?
It makes an infinite loop...
See here : http://plnkr.co/edit/ArVF1J06r8BxXCYwC4Db

**Comment by vguede** [comment]
I have an idea : use $timeout. Is it a good solution ?

**Comment by brandonroberts** [comment]
Not sure why its causes an infinite loop, could be an old router bug. Are you still using an old build?

**Comment by vguede** [comment]
I think I found the problem. It's due to your fix to templateUrl bug (see http://plnkr.co/edit/UzaDGOyeh6Qt7a0Wb22j?p=preview).
I updated angular_1_router with your last build and navigate works fine. When I add your fix, I must use $timeout to perform a navigate.
My plunker (http://plnkr.co/edit/ArVF1J06r8BxXCYwC4Db) is up to date.
Have you any idea to fix this ?

**Comment by brandonroberts** [comment]
It looks like a race condition between setting current controller. You could navigate from the $canActivate instead of the $routerOnActivate, or if / should always go to /admin, use a redirectTo instead of redirecting from within the home component

``` js
angular.module('app.home', [])
  .directive('home', HomeDirective);

function HomeDirective() {
  return {
    templateUrl: 'home.html',
    controller: ['$router', '$timeout', HomeController],
    controllerAs: 'home'
  };
}

HomeDirective.$canActivate = ['$router', function($router) {
  $router.navigate(['/Admin']);
  return false;
}];

HomeController = function() {
  this.name = 'World';
};
```

**Comment by vguede** [comment]
Good idea, but how access to routeParams in $canActivate ?

**Comment by vguede** [comment]
Here is 2 use cases :
- check routeParams and perform a redirect if there is any error
- load data and perform a redirect if there is any error

**Comment by brandonroberts** [comment]
You can inject `$nextInstruction` and `$prevInstruction` and access the params property.

``` js
Function.$canActivate = ['$router', '$nextInstruction', '$prevInstruction', function($router, next, prev) {
    // access next.params and prev.params
}];
```

**Comment by vguede** [comment]
it works perfectly ! Thanks a lot again !
