### ISSUE TITLE
"ng-outlet" directive has no content

### ISSUE THREAD

**Issue by vladimiry** [brandonroberts/angularjs-component-router#4]
Am I missing something?

https://www.dropbox.com/s/fzzwntkntk8ig11/angularjs-component-router.mp4?dl=1

**Comment by vladimiry** [comment]
Well, when I changed `code.angularjs.org/snapshot/angular.js` to `code.angularjs.org/1.5.0-rc.0/angular.js` in `/views/index.html` it became working.

**Comment by brandonroberts** [comment]
It looks like they have defaulted the restrict to 'E' with no way to override it, which currently makes it incompatible with the component router which uses attribute directives for routes. I'll get a fix in for this.

Thanks
