### ISSUE TITLE
What is the source/version of the router?

### ISSUE THREAD

**Issue by dmitriz** [brandonroberts/angularjs-component-router#5]
I wonder if the router here was ported directly from Angular2?
Is the `npm` package no more updated?

Would it be possible to have a reference to it for version tracking?

**Comment by brandonroberts** [comment]
Yes. Its built directly from the Angular 2 source as of beta.1, with one small fix for a missing function. The npm package isn't being updated yet, but I assume it will be updated in the future. I usually update the build file with each new beta.

**Comment by dmitriz** [comment]
Any link to the source files of the A2 repo?

**Comment by brandonroberts** [comment]
Yep: https://github.com/angular/angular

Angular 1 Router: https://github.com/angular/angular/tree/master/modules/angular1_router

**Comment by dmitriz** [comment]
Thanks, I see you need to build it, tried to clone and run `gulp build` but got some "process out of memory" :(

**Comment by brandonroberts** [comment]
If you just want to build the Angular 1 router, just do `gulp buildRouter.dev` and it will produce the `angular_1_router.js` in the `dist` folder

**Comment by dmitriz** [comment]
That works, thanks!

**Comment by brandonroberts** [comment]
:+1:

**Comment by ArniDzhan** [comment]
Hi @brandonroberts I am trying to import angular_1_router.js into my main.js and see error about missing modules when 1require('') ;1 are run
`var instruction_1 = require('./instruction');`

I am using this project as a seed and trying to import generated angular_1_router.js file just like any other library
https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/blob/master/app/js/main.js

any ideas?

**Comment by brandonroberts** [comment]
@ArniDzhan the angular 1 router as built from source won't work with a browserify build. It has `require` statements in it which get treated as imports by browserify. Basically you need to change all the places where it has `require('` to something else like `routerRequire('`.

**Comment by ArniDzhan** [comment]
> @ArniDzhan the angular 1 router as built from source won't work with a browserify build. It has require statements in it which get treated as imports by browserify. Basically you need to change all the places where it has require(' to something else like routerRequire('.

@brandonroberts thanks for quick reply, after changing the name build goes through but I get routerRequire function undefined error in browser debugger. Stuck there at the moment.

**Comment by ArniDzhan** [comment]
found it, had to also change
`var router = function () {return exports;};`
to
`var routerRequire = function () {return exports;};`

Thanks for your help

**Comment by brandonroberts** [comment]
:+1:
