### ISSUE TITLE
$routeOnActivate won't be called when using templateUrl

### ISSUE THREAD

**Issue by subesokun** [brandonroberts/angularjs-component-router#6]
Hi,

thanks a lot for sharing your example application! I was playing a bit around with it, especially I was interested in the $routerOnActivate function. If I use your application as it is everything works fine but as soon as I use a `templateUrl` instead of inlining the template via `template` the $routeOnActivate function won't be called anymore (e.g. here https://github.com/brandonroberts/angularjs-component-router/blob/master/app/routes/about/about.js#L5). I know this is not an issue of your sample application but maybe you've an guess what goes wrong.

Thanks a lot!

**Comment by brandonroberts** [comment]
Its a known issue. See https://github.com/angular/angular/issues/4633

**Comment by subesokun** [comment]
Oh I see, thanks! Closing this issue and watching the process on the Angular issue.
