### ISSUE TITLE
Activate router hook

### ISSUE THREAD

**Issue by lucianogreiner** [brandonroberts/angularjs-component-router#8]
Hello.

Is there a way to declare a "activate" router hook inside a component? I am trying to resolve some data before controller invocation, but either $activate/activate/$routerOnActivate is never called. On the other hand $canActivate seems to work.

**Comment by brandonroberts** [comment]
If you're using a `templateUrl` in your component, there is an existing bug where the $routerOnActivate hook isn't called. There is a pending PR for it here: https://github.com/angular/angular/pull/6978. Once that gets merged in and the build is updated then that hook will work correctly. It will work fine if you use a `template` in your component

**Comment by lucianogreiner** [comment]
Yeah, makes sense. I do also wonder why the name $routerOnActivate instead of just $activate, since $canActivate works.

Thank you mate

**Comment by brandonroberts** [comment]
No problem. It was originally $onActivate, but was renamed to avoid possible collisions with other lifecycle hooks in Angular 2 outside of the router.
