### ISSUE TITLE
loader-function

### ISSUE THREAD

**Issue by manfredsteyer** [brandonroberts/angularjs-component-router#9]
Hi,

I've noticed, that we can use a loader-function instead of a component within a router-config-object. The question is, how to use it, to load a component dynamically?

Is that even supported in 1.x or do I have to use community-extensions?

Wishes,
Manfred

**Comment by brandonroberts** [comment]
Lazy loading of components is not built in to 1.x, but it is supported through community-extensions such as http://oclazyload.readme.io.

I might add an example of lazy loading to the example app that uses this functionality.

**Comment by manfredsteyer** [comment]
Thanks for this info. And Btw: thanks for this wonderful Demo-Repository. It really helped me with this topic!!

**Comment by brandonroberts** [comment]
:+1:
